### ISSUE TITLE
Melhorar base de dados.

### ISSUE THREAD

**Issue by jorgeluizmcf** [jorgeluizmcf/Graflix#3]
# Adicionar filmes ao Graflix

## Descrição

Para melhorar a experiência de recomendações no **Graflix**, precisamos adicionar uma coleção mais ampla de filmes ao banco de dados. A tarefa consiste em popular o arquivo `data.json` com **50 filmes** e suas respectivas imagens, garantindo que o sistema tenha uma boa base de dados para gerar recomendações precisas e interessantes para os usuários.

## Objetivo

- **Adicionar 50 filmes** ao arquivo `/src/data/data.json`.
- **Inserir as imagens** respectivas de cada filme no diretório `/src/img/`, usando o nome do filme como o nome do arquivo de imagem (`nome-do-filme.jpg`).
- Garantir que as imagens sejam adequadas (preferencialmente de tamanho médio a grande para uma boa exibição).
- Incluir um texto de sinopse para cada filme.

## Tarefas

1. **Identificar filmes populares** e de diferentes gêneros para garantir uma diversidade nas recomendações.
2. **Adicionar as informações dos filmes** ao arquivo JSON, incluindo:
   - Título do filme
   - Ano de lançamento
   - Gênero(s)
   - Sinopse
   - URL da imagem
3. **Baixar e salvar as imagens** no diretório `/src/img/`, nomeando-as de acordo com o título do filme (por exemplo: `nome-do-filme.jpg`).
4. **Verificar se as imagens estão corretamente associadas** aos filmes no arquivo JSON.
5. **Incluir sinopse** para todos os filmes.

## Requisitos

- Certifique-se de que cada entrada no `data.json` siga o formato correto de dados.
- As imagens devem ser de boa qualidade e de um tamanho razoável, adequadas para exibição no frontend.

## Exemplo de formato para o arquivo `data.json`:

```json
[
  {
    "title": "Nome do Filme",
    "year": 2023,
    "genre": ["Ação", "Aventura"],
    "synopsis": "Sinopse breve do filme.",
    "image": "/src/img/nome-do-filme.jpg"
  },
  {
    "title": "Outro Filme",
    "year": 2021,
    "genre": ["Drama", "Romance"],
    "synopsis": "Outra sinopse interessante.",
    "image": "/src/img/outro-filme.jpg"
  }
]

**Comment by jmateus-peixoto** [comment]
Feito
[data.json](https://github.com/user-attachments/files/17923788/data.json)
