### ISSUE TITLE
Criar identificação visual para o Graflix.

### ISSUE THREAD

**Issue by jorgeluizmcf** [jorgeluizmcf/Graflix#4]
# Criar Identificação Visual para o Graflix

## Descrição

Para melhorar a apresentação e a identidade do **Graflix**, precisamos criar uma identidade visual coerente e profissional para a aplicação. A identidade visual deve seguir a paleta de cores e o estilo de design utilizado pelo **Netflix**, servindo como referência, pois o Graflix é uma aplicação acadêmica focada no aprendizado de sistemas de recomendações de filmes.

### Objetivos

1. **Desenvolver um logotipo** que represente o Graflix, inspirado no estilo visual do Netflix, mas com um toque único que remeta ao propósito acadêmico da plataforma.
2. **Definir a paleta de cores** para o Graflix, adotando as cores principais do Netflix, com pequenas modificações se necessário, para evitar plágio, mas manter a similaridade.
3. **Criar tipografia** coerente com o design do Netflix, respeitando a legibilidade e simplicidade.
4. **Desenvolver elementos visuais** como botões, ícones e banners que sigam a linha do design do Netflix, para garantir uma experiência de usuário fluída e profissional.

## Requisitos

- **Logotipo**: Deve ser simples, marcante e fácil de ser reconhecido, com um estilo moderno e minimalista. O logotipo pode incluir um ícone relacionado a filmes (como uma claquete ou rolo de filme) combinado com o nome "Graflix".
  
- **Paleta de Cores**: A paleta de cores deve ser inspirada nas cores do Netflix, como vermelho, preto e branco, mas com uma adaptação que faça o Graflix se destacar por conta própria.
  
  - **Cores principais**:
    - Vermelho (#E50914)
    - Preto (#141414)
    - Branco (#FFFFFF)
    - Tons de cinza para equilíbrio e contraste
  
- **Tipografia**: A tipografia deve ser moderna e simples, mantendo o foco na legibilidade. Podemos adotar fontes semelhantes às utilizadas pelo Netflix, como "Gloock" ou fontes sem serifa e de fácil leitura.

- **Elementos visuais**:
  - **Botões**: Devem ter uma aparência limpa e moderna, como os botões do Netflix, com bordas arredondadas e efeitos de hover.
  - **Ícones**: Ícones pequenos e intuitivos para facilitar a navegação (por exemplo, ícones de gênero de filme, como ação, comédia, etc.).
  - **Banners e Cards**: As imagens de filmes devem ser destacadas em cards com bordas arredondadas e uma paleta de cores contrastante com o fundo.

## Exemplos e Inspirações

1. **Netflix Logo**:
   - O logotipo da Netflix tem um estilo simples e moderno, com uma tipografia customizada e ícones minimalistas.
   
2. **Cores do Netflix**:
   - A paleta de cores do Netflix é composta principalmente de vermelho, preto e branco, com ênfase em contraste e simplicidade.
   
3. **Layout do Netflix**:
   - O layout do Netflix é centrado em torno de imagens grandes de filmes e séries, com uma navegação simples e direta.

## Tarefas

1. **Desenvolver o logotipo** para o Graflix com base na paleta e estilo de design sugerido.
2. **Escolher a paleta de cores** para a interface da aplicação, com base na paleta do Netflix.
3. **Selecionar ou criar a tipografia** que será usada na interface do usuário (UI).
4. **Criar ícones e elementos de navegação** que sejam modernos e simples.
5. **Aplicar a identidade visual** no layout da aplicação Graflix (home page, páginas de filmes, etc.).
6. **Testar e ajustar a estética visual** da aplicação, garantindo uma boa experiência de usuário.

## Notas

- A identidade visual deve ser profissional, mas também refletir o ambiente acadêmico da aplicação. Deve se manter moderna e funcional, garantindo que os usuários se sintam atraídos e confortáveis enquanto navegam.
- Lembre-se de que, apesar de ser inspirado no design do Netflix, a identidade visual do Graflix deve ser única, refletindo sua natureza de projeto acadêmico.

---

**Comment by jmateus-peixoto** [comment]
Feito
![favicon](https://github.com/user-attachments/assets/c0784464-35c5-4e01-be10-9e86dc97922c)
![logo_graflix](https://github.com/user-attachments/assets/36cf84d7-e43c-45c8-a70b-44f9b994928d)
